---
title: "designing_a_simulation_sampling_scheme"
author: "Jessie Berta-Thompson"
date: "January 18, 2017"
output: html_document
---

## Sampling from simulations
The dataset generated by these simulations would be too big if we kept every generation. 
Instead, we sample throughout time at fixed intervals. 
Here, playing with R tools to set those intervals



```{r}
#First try

#How many times to replicate simulation?
rep <- 20 # set number of replicate simulations

#How many generations to run each simulation?
maxgen <- 10000 # also like years

#Which generations would you like to keep to analyze later?
howmany <- 100 # how many times do you want to keep data
samplegens <- floor(seq(1,maxgen, maxgen/howmany))

print(samplegens)

#In addition to this, we sample initial(0) and final(10000 in this example) times.
```

This works well, but values are a little odd.
0, 100, 200, 9900 would be easier to read off a plot

## Fixed interval sampling

```{r}
#How many generations to run each simulation?
maxgen <- 10000 # also like years

#How many years between taking samples for later analysis?
interval <- 100 # sample every n years

samplegens <- seq.int(interval, maxgen-interval, interval)

print(samplegens)
#In addition to this samplingly while running, we sample initial(0) and final(10000 in this example) times.
#These do not need to be in this list
#For a total of n samples:
nsamples = length(samplegens) + 2
print(sprintf("A total of %s samples will be taken over time, saving information about individuals at start, end and every %s years", nsamples, interval))



```